subject_list = [
  "Adult Children",
  "Alcoholics Anonymous",
  "Affirmation",
  "Anxiety",
  "Behavior Modification",
  "Business Ethics",
  "Change (Psychology)",
  "Character",
  "Children AND Management",
  "Christian Life",
  "Christian AND Psychology",
  "Christ-Psych",
  "Codependence",
  "Compulsive Behavior",
  "Conduct of Life",
  "Courtship",
  "Dating",
  "Depression",
  "Diet",
  "Divorce",
  "Drug Abuse",
  "Etiquette",
  "Etiquette AND Children",
  "Fathers",
  "Happiness",
  "Hygiene AND Sexual",
  "Interpersonal AND Relationships",
  "Intimacy",
  "Marriage",
  "Meditation",
  "Men AND Conduct of Life",
  "Mental Health",
  "Mental Healing",
  "Mental Suggestion",
  "Mind and Body",
  "Mothers",
  "Parent and Child",
  "Personality",
  "Psychology Applied",
  "Reducing OR Corpulence OR Reducing Exercises OR Reducing Diets",
  "Relationship Addiction",
  "Self",
  "Self-Acceptance",
  "Self-Actualization",
  "Self-Confidence",
  "Self-Control",
  "Self-Culture",
  "Self-Esteem",
  "Self-Help",
  "Self-Help AND Technology",
  "Self-Help Groups",
  "Self-Perception",
  "Self-Realization",
  "Self-Reliance",
  "Self-Respect",
  "Self-Talk",
  "Sex Addiction",
  "Sex Instruction",
  "Sex Instruction AND Children",
  "Spiritual Life OR Sprirituality",
  "Spiritualism",
  "Stress",
  "Stress Management",
  "Substance Abuse",
  "Success",
  "Twelve-Step Programs",
  "Women AND Conduct of Life",
  "Young Men",
  "Young Women",
  "Youth",
  "Youth AND Conduct of Life",
  "Youth AND Religious"
]
