subject_list = [
  "Adult Children",
  "Alcoholics Anonymous",
  "Affirmation",
  "Anxiety",
  "Behavior Modification",
  "Bibliotherapy",
  "Business Ethics",
  "Change (Psychology)",
  "Character",
  "Children AND Management",
  "Christian Life",
  "Christian AND Psychology",
  "Codependence",
  "Compulsive Behavior",
  "Conduct of Life",
  "Courtship",
  "Dating",
  "Dependency (Psychology)",
  "Depressed Persons",
  "Depression",
  "Depression Mental",
  "Diet",
  "Divorce",
  "Drug Abuse",
  "Etiquette",
  "Etiquette AND Children",
  "Fathers",
  "Happiness",
  "Hygiene AND Sexual",
  "Interpersonal AND Relationships",
  "Intimacy",
  "Marriage",
  "Meaning (Psychology)",
  "Meditation",
  "Men AND Conduct of Life",
  "Mental Health",
  "Mental Healing",
  "Mental Suggestion",
  "Mind and Body",
  "Mothers",
  "Parent and Child",
  "Personality",
  "Psychic Trauma",
  "Psychology Applied",
  "Reducing OR Corpulence OR Reducing Exercises OR Reducing Diets",
  "Relationship Addiction",
  "Self",
  "Self-Acceptance",
  "Self-Actualization",
  "Self-Confidence",
  "Self-Control",
  "Self-Culture",
  "Self-Defeating Behavior",
  "Self-Destructive Behavior",
  "Self-Esteem",
  "Self-Hate (Psychology)",
  "Self-Help",
  "Self-Help Techniques",
  "Self-Help Groups",
  "Self-Management",
  "Self-Perception",
  "Self-Presentation",
  "Self-Realization",
  "Self-Reliance",
  "Self-Respect",
  "Self-Talk",
  "Sex Addiction",
  "Sex Instruction",
  "Sex Instruction AND Children",
  "Spiritual Life OR Sprirituality",
  "Spiritualism",
  "Stress",
  "Stress Management",
  "Substance Abuse",
  "Success",
  "Twelve-Step Programs",
  "Women AND Conduct of Life",
  "Young Men",
  "Young Men AND Religious",
  "Young Women",
  "Young Women AND Religious",
  "Youth",
  "Youth AND Conduct of Life",
  "Youth AND Religious Life",
  "Baseball",
  "Personal Finance",
  "Cookery",
  "Total Titles"
]
